
build_script:
- set
# - dir "C:\Program Files\PostgreSQL" || date /t (SOLE WINNER)
# - dir "C:\Program Files (x86)\PostgreSQL" || date /t
# - dir "C:\Program Files(x86)\PostgreSQL" || date /t
# - dir "C:\ProgramFiles\PostgreSQL" || date /t
# - dir "C:\ProgramFiles (x86)\PostgreSQL" || date /t
# - dir "C:\ProgramFiles(x86)\PostgreSQL" || date /t
