
image: Visual Studio 2019

build_script:
# - set
# - dir "C:\Program Files\PostgreSQL" || date /t
# - dir "C:\Program Files (x86)\PostgreSQL" || date /t
# - dir "C:\Program Files(x86)\PostgreSQL" || date /t
# - dir "C:\ProgramFiles\PostgreSQL" || date /t
# - dir "C:\ProgramFiles (x86)\PostgreSQL" || date /t
# - dir "C:\ProgramFiles(x86)\PostgreSQL" || date /t


- if "1"=="1" (
    set alpha=true
    set beta=false &
    if "%beta%"=="false" (
        set gamma=false &
        set delta=true 
      )
  ) else (
    set alpha=false &
    set beta=true
  )
- echo %alpha%
- echo %beta%
- echo %gamma%
- echo %delta%
