
image: Visual Studio 2015

environment:
  matrix:
    - PlatformToolset: v141
      configuration: Release
      platform: x86
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

install:
#   #
#   - if %PLATFORM%==x64 (set BIT=64) else set BIT=32
#   - set betterperlurl=https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-%BIT%bit-portable.zip
#   - set betterperl=strawberry%BIT%
#   - if not exist %betterperl%.zip curl -o %betterperl%.zip %betterperlurl%
#   - 7z x %betterperl%.zip -oc:\%betterperl%
#   - set Path=c:\%betterperl%\perl\bin;%Path%
#   - which perl
#   - set Path=%Path%;c:\%betterperl%\c\bin
#   #

build_script:
  - cl /?
  - set
  - # bash -login -c "which cl 2>/dev/null"
  - set Path=%VCToolsInstallDir%\bin\Host%PLATFORM%\%PLATFORM%;%Path%
  - set
  - cl /?
  - cd %VSSDK140Install%
  - tree
  - # bash -login -c "find /c -name '*cl.exe'       -print 2>/dev/null"
  - # bash -login -c "find /c -name '*vcvars64.bat' -print 2>/dev/null"
  - dir "C:\Program Files (x86)"
  - dir "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin"
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl" /?'

# DIES NOT FOUND - which cl
# - set
# - dir "C:\Program Files\PostgreSQL" || date /t
# - dir "C:\Program Files (x86)\PostgreSQL" || date /t
# - dir "C:\Program Files(x86)\PostgreSQL" || date /t
# - dir "C:\ProgramFiles\PostgreSQL" || date /t
# - dir "C:\ProgramFiles (x86)\PostgreSQL" || date /t
# - dir "C:\ProgramFiles(x86)\PostgreSQL" || date /t

# - if "1"=="1" (
#     set alpha=true &
#     set beta=false &
#     set beta2=false &
#     if "%beta%"=="false" (
#         set gamma=false &
#         set delta=true
#       )
#   ) else (
#     set alpha=false &
#     set beta=true
#   )
# - echo %alpha%
# - echo %beta%
# - echo %beta2%
# - echo %gamma%
# - echo %delta%

# - if "1"=="1" (
#     set alpha=true
#     set beta=false
#   )
#   echo %alpha%
#   echo %beta%

