

#
version: 1.0.{build}.{branch}
#

environment:
  AUTHOR: Andre Mikulec
  MATVARIABLE: root
  ENVVARIABLE: forroot

  matrix:
  - MATVARIABLE: matvar1
  - MATVARIABLE: matvar2
    
    
init:
  - echo %ENVVARIABLE%
  - echo root init
    
install:
  - echo root install
   
before_build:
  - echo root before_build
  
build_script:
  - echo root build_script
    
for:

-
  matrix:
    only:
      - MATVARIABLE: matvar1

  environment:
    ENVVARIABLE: for1
    
  init:
    - echo %ENVVARIABLE%
    - echo matvar1 init
      
  install:
    - echo matvar1 install
     
  before_build:
    - echo matvar1 before_build
    
  build_script:
    - echo matvar1 build_script


-
  matrix:
    only:
      - MATVARIABLE: matvar2

  environment:
    ENVVARIABLE: for2
    
  init:
    - echo %ENVVARIABLE%
    - echo matvar2 init
      
  install:
    - echo matvar2 install
     
  before_build:
    - echo matvar2 before_build
    
  build_script:
    - echo matvar2 build_script

