
#
version: 1.0.{build}.{branch}
#

environment:
  AUTHOR: Andre Mikulec
  MATVARIABLE: root
  ENVVARIABLE: forroot

  matrix:
  - MATVARIABLE: matvar1
  - MATVARIABLE: matvar2

install:
  - echo root install %MATVARIABLE%

before_build:
  - echo root before_build %MATVARIABLE%



for:

-
  matrix:
    only:
      - MATVARIABLE: matvar1

  environment:
    ENVVARIABLE: for1

  init:
    - echo %ENVVARIABLE%
    - echo matvar1 init %MATVARIABLE%

  build_script:
    - echo matvar1 build_script %MATVARIABLE%

  test_script:
    - echo matvar1 test_script %MATVARIABLE%

-
  matrix:
    only:
      - MATVARIABLE: matvar2

  environment:
    ENVVARIABLE: for2

  init:
    - echo %ENVVARIABLE%
    - echo matvar2 init %MATVARIABLE%

  build_script:
    - echo matvar2 build_script %MATVARIABLE%

  test_script:
    - echo matvar2 test_script %MATVARIABLE%



cache:
- item.txt


artifacts:
- path: 'plr-*.zip'
  name: plr_zip
- path: 'pg-*.zip'
  name: pg_zip

deploy:

  - provider: FTP
    host: frs.sourceforge.net
    protocol: sftp
    username: andremikulec,andremikulec.u
    password:
      secure: 4gk4GyW4O5RooiOyGeRdoA==
    artifact: pg_zip, plr_zip
    folder: /home/frs/project/andremikulec
    application:
    active_mode: false